version: 2.1

jobs:
  build:
    working_directory: ~/project
    docker:
      - image: gradle:8.12.1-jdk17
    steps:
      - checkout
      - run:
          name: Build
          command: gradle assemble
      - run:
          name: Test
          command: gradle test
      - store_test_results:
          path: junker.dev/build/test-results
  deploy-prod:
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - checkout
      - run:
          name: Deploy
          command: ssh -oStrictHostKeyChecking=no -v $USER@$IP "./deploy_project.sh"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy-prod:
          requires:
            - build
          filters:
            branches:
              only: main
